CREATE TYPE StudentAssessmentType AS ENUM ('TWO', 'THREE', 'FOUR', 'FIVE');
CREATE TYPE ClassNumberType AS ENUM ('ONE', 'TWO', 'THREE', 'FOUR', 'FIVE', 'SIX', 'SEVEN', 'EIGHT', 'NINE', 'TEN', 'ELEVEN');
CREATE TYPE GroupScheduleType AS ENUM ('FIRST', 'SECOND', 'JOINT');
CREATE TYPE GroupStudentType AS ENUM ('FIRST', 'SECOND');
CREATE TYPE GenderType AS ENUM ('MALE', 'FEMALE');
CREATE TYPE CountGroupType AS ENUM ('ONE', 'TWO');
CREATE TYPE DayOfWeekType AS ENUM ('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY');
CREATE TYPE NameRole AS ENUM ('STUDENT', 'TEACHER', 'ADMIN');
